apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: civo-argo-rollouts-tutorial
  newName: avik6028/civo-argo-rollouts-tutorial
  newTag: d1780b2f8d2487cf1a0e757b2d492c1b713c6fa7
