apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: civo-tutorial
images:
- name: civo-argo-rollouts-tutorial
  newName: avik6028/civo-argo-rollouts-tutorial
  newTag: aed5c620f93b53b926f90b66ff43fbeb7fd08284
