apiVersion: v1
kind: Service
metadata:
  name: svc-active
  namespace: civo-tutorial
  labels:
    app: sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 1337
  selector:
    app: sample-app